repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
  - repo: local
    hooks:
      - id: shellcheck
        name: Run static analysis (shellcheck)
        entry: shellcheck
        language: system
        files: \.(sh|bash)$
        types: [ file ]
        alias: shck
        args: [ '-x', '-P', 'SCRIPTDIR', '-e', 'SC2034' ]
      - id: shfmt
        name: Run lint check (shfmt -d)
        entry: shfmt
        language: system
        files: \.(sh|bash)$
        types: [ file ]
        args: [ '-w', '-i', '0', '-ci', '-sr', '-d', '-s' ]
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.6.2
    hooks:
      - id: golangci-lint
        args: ["--fix"]
